//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditors
    {
        public Creditors()
        { }
        public Creditors(string IBAN, string name, double lend, DateTime end, double interest, int banker_id)
        {
            this.IBAN = IBAN;
            this.name = name;
            this.lend = lend;
            this.endDate = end;
            this.interest = interest;
            this.banker_id = banker_id;
            this.guarantee = Logic.Calculate.Guarantee(lend, interest);
        }
        public int Id { get; set; }
        public string IBAN { get; set; }
        public string name { get; set; }
        public double lend { get; set; }
        public System.DateTime endDate { get; set; }
        public double interest { get; set; }
        public double guarantee { get; set; }
        public int banker_id { get; set; }
    
        public virtual bankers bankers { get; set; }
    }
}
